language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.5-dev # 3.5 development branch
  - 3.6-dev # 3.6 development branch
  - nightly # currently points to 3.7-dev
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=antfs_cli setup.py test
  - python setup.py install
  - antfs-cli --help
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: 3.5-dev
    - python: 3.6-dev
    - python: nightly
